from .Custos_Operacionais import init_db_custos_operacionais
from .Esportes import init_db_esportes
from .Previsao_Lucro import init_db_previsao_lucro
from .Produtos import init_db_produtos
from .Proprietarios_Quadra import init_db_proprietarios_quadra
from .Quadra_Esporte import init_db_quadra_esporte
from .Quadras import init_db_quadras
from .Receitas import init_db_receitas
from .Reservas import init_db_reservas
from .Usuarios import init_db_usuarios
from .Vendas_Produtos import init_db_venda_produtos